INSERT INTO ROLE VALUES('Admin');
SELECT * FROM ROLE;

INSERT INTO PERMISSIONS VALUES('INSERT');
INSERT INTO PERMISSIONS VALUES('UPDATE');
INSERT INTO PERMISSIONS VALUES('SELECT');
INSERT INTO PERMISSIONS VALUES('DELETE');
INSERT INTO PERMISSIONS VALUES('USER');
INSERT INTO PERMISSIONS VALUES('REPORT');
INSERT INTO PERMISSIONS VALUES('BULK LOADING');

SELECT * FROM PERMISSIONS
ORDER BY PID;

INSERT INTO RolePermissions VALUES(1, 1);
INSERT INTO RolePermissions VALUES(1, 2);
INSERT INTO RolePermissions VALUES(1, 3);
INSERT INTO RolePermissions VALUES(1, 4);
INSERT INTO RolePermissions VALUES(1, 5);
INSERT INTO RolePermissions VALUES(1, 6);
INSERT INTO RolePermissions VALUES(1, 7);

SELECT * FROM RolePermissions;

INSERT INTO Company VALUES ('COM-001', 'Common Company', 'A base company for all unassigned users');
SELECT * FROM Company;

INSERT INTO ProductType VALUES ('Common Product');
SELECT * FROM ProductType;